### ISSUE TITLE
Badge is not being styled

### ISSUE THREAD

**Issue by abevoelker** [rsanheim/honey_badger#3]
The `honey_badger` helper generates this HTML:

``` html
<div class="corner-banner honey-badger development">development</div>
```

However, the CSS generated by SASS looks like this (using sass 3.1.19):

``` css
.development .corner-banner.honey-badger {
}
```

Note the space between `.development` and `.corner-banner.honey-badger`.  I can get the badge to be styled by changing the HTML with Chrome dev tools to this:

``` html
<div class="development">
  <div class="corner-banner honey-badger">development</div>
</div>
```

but I assume that the SASS should probably be changed so that only one div is needed.

**Comment by jgkite** [comment]
See the "Customization" section of the [Readme](https://github.com/rsanheim/honey_badger/blob/master/README.markdown) for how to set different colors for different environments. It would be more elegant if there were sensible defaults for the environment-specific badges; we welcome a pull request!

**Comment by abevoelker** [comment]
Nevermind, it looks to be working straight from the git repo.  It's just the latest version from RubyGems (0.0.4) doesn't seem to be working (or perhaps the docs are just out of date for that version).  You might wanna bump to 0.0.5 and push it to RubyGems.

**Comment by nacengineer** [comment]
+1 on @abevoelker's comment to bump the version and push a new one to rubygems
