### ISSUE TITLE
Extra space in the generated css declaration

### ISSUE THREAD

**Issue by noozo** [rsanheim/honey_badger#5]
Hi, when using this on my rails app i noticed that there is an extra space on the generated honey_badger.css file. This prevents the ribbon from being properly drawn:

.development .corner-banner.honey-badger {  

instead of 

.development.corner-banner.honey-badger {  

Cheers,
Pedro

**Comment by rsanheim** [comment]
That space should be there, right @jgkite ?

**Comment by noozo** [comment]
If it should, then it's not working on OSX, Google Chrome, and rails 3.2.9. If i copy the entire CSS to a new file and remove the space: Presto! :)

**Comment by jgkite** [comment]
It just means the "development" class should be on a container, like the <body> tag.

**Comment by rsanheim** [comment]
Yeah that is what I thought - just change your container markup, @nocivus .

**Comment by noozo** [comment]
Thing is... you guys are the ones generating the container markup, with this:

<%= honey_badger unless Rails.env.production? %>

:)

**Comment by rsanheim** [comment]
Oh are you talking about the dummy controller stuff?  That may be out of date with the actual markup you are supposed to use in your own app.  So that could be a legit bug.

**Comment by noozo** [comment]
The generated markup is:

<div class="corner-banner honey-badger development">development</div>

**Comment by noozo** [comment]
Oops, it ate the formatting :)

`<div class="corner-banner honey-badger development">development</div>`
